- id: doi:10.1109/TMRB.2019.2949881
  type: paper
  description: >
    This paper presents an adaptive field-of-view control method for robotic
    laparoscopic systems using programmable composed constraints, enabling
    robust visual servoing and improved surgical scene awareness.
  tags:
    - medical robotics
    - visual servoing
    - laparoscopic surgery
    - constrained control
