- id: doi:10.1109/TMRB.2019.2949881
  type: paper
  description: >
    This paper presents an adaptive field-of-view control method for robotic
    laparoscopic systems using programmable composed constraints, enabling
    robust visual servoing and improved surgical scene awareness.
  tags:
    - medical robotics
    - visual servoing
    - laparoscopic surgery
    - constrained control
    
 - id: doi:10.1109/LRA.2022.3191964
  type: paper
  description: >
    This paper presents an easy-to-deploy combined nasal and throat swab robot
    that achieves high sampling dexterity while remaining robust to external
    interference, enabling safe and effective medical sampling through
    soft robotic design.
  tags:
    - medical robotics
    - soft robotics
    - teleoperation
    - healthcare automation
    
- id: doi:10.1109/IROS60139.2025.11246163
  type: paper
  description: >
    This paper presents a data-driven visual servoing approach for flexible
    continuum robots operating in constrained environments, enabling robust
    real-time control under uncertainty and external constraints.
  tags:
    - visual servoing
    - continuum robots
    - constrained environments
    - data-driven control
    - robotics  
  
